version: "3.9"

services:
  go_blok_doh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5353:53/udp"   
    volumes:
      - ./config:/app/config    # Mount volume ke host
    restart: always
